### ISSUE TITLE
Running `pod install` failed while building HLP for the first time.

### ISSUE THREAD

**Issue by berlin-ab** [alexbasson/SwiftDIHLP#1]
```

±  |tag:0.0.13 ✓| → pod install
Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    project 'path/to/Project.xcodeproj'


  |2.3.1| pivotal-wifi-3-183 in ~/workspace/SwiftDI/SwiftDIHLP
±  |tag:0.0.13 U:31 ✗| → less README.md

  |2.3.1| pivotal-wifi-3-183 in ~/workspace/SwiftDI/SwiftDIHLP
±  |tag:0.0.13 U:31 ✗| → less README.md

  |2.3.1| pivotal-wifi-3-183 in ~/workspace/SwiftDI/SwiftDIHLP
±  |tag:0.0.13 U:31 ✗| → swift package generate-xcodeproj
generated: ./SwiftDIHLP.xcodeproj

  |2.3.1| pivotal-wifi-3-183 in ~/workspace/SwiftDI/SwiftDIHLP
±  |tag:0.0.13 U:31 ✗| → pod install
Analyzing dependencies
Downloading dependencies
Using Nimble (6.0.1)
Using Quick (1.0.0)
Generating Pods project
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/aberlin/.rbenv/versions/2.3.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1217)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.11.0
Ruby lib dir : /Users/aberlin/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b318bd17aef3573c8f206a2d160b626f07e2bfa7
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'SwiftDIHLP' do
  use_frameworks!

  target 'SwiftDIHLPTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end

end
```

### Error

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`OBJ_32`>:Xcodeproj::Project::Object::PBXFileReference
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:79:in `set_target_xcconfig'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `block (2 levels) in integrate'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:58:in `block in integrate!'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:57:in `integrate!'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:612:in `block in integrate_user_project'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:609:in `integrate_user_project'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:117:in `install!'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/aberlin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/Users/aberlin/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/aberlin/.rbenv/versions/2.3.1/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60files%27+for+%3CPBXFileReference+path%3D%60Pods%60+UUID%3D%60OBJ_32%60%3E%3AXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXFileReference&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

```

**Comment by alexbasson** [comment]
It appears as though Cocoapods can't find the `.xcodeproj` file. Did you
make sure to run `swift package generate-xcodeproj` first?
